name: Build Check

on: [push, pull_request]

jobs:
  build-host:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win64
            architecture: x64
          - os: macos-latest
            artifact-name: macOS
            architecture: x64
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch all history and metadata
        run: git fetch --prune --unshallow
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
          architecture: ${{ matrix.architecture }}

      - name: Build with Gradle
        run: ./gradlew nt_robot_controllerReleaseExecutable

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: build/exe/nt_robot_controller/release

  update-controllers:
    name: Update controllers on Overture-Webots
    needs: [build-host]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: executables
      - name: Clone Overture Webots
        run: |
          git clone https://github.com/overture-7421/Overture-Webots.git --depth 1
      - name : Set up git
        run: |
          cd Overture-Webots
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Transfer executables
        run: |
          mkdir -p Overture-Webots/controllers/nt_robot_controller/
          rm Overture-Webots/controllers/nt_robot_controller/*
          find executables -type f -exec chmod +x '{}' ';'
          find executables -type f -exec mv -i '{}' Overture-Webots/controllers/nt_robot_controller/ ';'
      - name: Commit
        run: |
          cd Overture-Webots
          git add .
          git commit -m "Update controllers to latest version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: overture-7421/Overture-Webots
          github_token: ${{ secrets.ACCESS_TOKEN }}
          directory: Overture-Webots