name: Build Check

on: [push, pull_request]

jobs:
  build-host:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win64
            architecture: x64
          - os: macos-latest
            artifact-name: macOS
            architecture: x64
          - os: ubuntu-latest
            artifact-name: linux
            architecture: x64
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch all history and metadata
        run: git fetch --prune --unshallow
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
          architecture: ${{ matrix.architecture }}

      - name: Build with Gradle
        run: ./gradlew nt_robot_controllerReleaseExecutable